stages:
  - build-deploy
develop-build-deploy:
  stage: build-deploy
  only:
    - /^develop#.+$/
  except:
    - branches
  script:
    - |
      #!/bin/bash
      sudo rm -rf /data/www/schoolly-enduser/.nuxt
      npm install
      npm run build
      sudo rsync -aurvh --include='.nuxt/***' --include='.env' --include='package.json' --include='ecosystem.config.js' --include='assets/***' --include='static/***' --exclude='*' ./ /data/www/schoolly-enduser/
      sudo su - famtech -c "pm2 restart SchoollyApp"
  tags:
    - develop
staging-build-deploy:
  stage: build-deploy
  only:
    - /^staging#.+$/
  except:
    - branches
  script:
    - |
      #!/bin/bash
      sudo rm -rf /data/www/staging/schoolly-enduser/.nuxt
      npm install
      npm run build
      sudo rsync -aurvh --include='.nuxt/***' --include='.env' --include='package.json' --include='ecosystem.config.js' --include='assets/***' --include='static/***' --exclude='*' /data/www/staging/schoolly-enduser/
      sudo su - famtech -c "pm2 restart SchoollyAppStaging"
  tags:
    - staging